### ISSUE TITLE
OpenSSL

### ISSUE THREAD

**Issue by muv1** [mback2k/curl-docker-winbuildenv#1]
Sorry if this is wrong place for this, but here:

https://dl.uxnr.de/build/curl

requires OpenSSL, but I dont see that provided on that site. The cURL static library is not much use without transitive dependencies. See here for example:

https://curl.haxx.se/windows

**Comment by mback2k** [comment]
The builds at dl.uxnr.de are no longer maintained. The static builds (_stc) should include all dependencies since they have been compiled statically. OpenSSL should not be required, as those builds use the Windows Crypto APIs and Schannel for HTTPS. https://curl.haxx.se/windows is not related to this repository or https://dl.uxnr.de/build/curl, please take a look here: https://github.com/curl/curl-for-win.
